// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2d2QQi_kCneZ9RqzM_Yc8zePIoAfJ6ik',
    appId: '1:597928996925:web:aca0e16bc28815541afa54',
    messagingSenderId: '597928996925',
    projectId: 'ai-calenda',
    authDomain: 'ai-calenda.firebaseapp.com',
    storageBucket: 'ai-calenda.appspot.com',
    measurementId: 'G-6D5Q2LRY0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyawjwu1t-X2yPrA55pJjONDo5cdoy55Y',
    appId: '1:597928996925:android:a3222bd03e38b2e81afa54',
    messagingSenderId: '597928996925',
    projectId: 'ai-calenda',
    storageBucket: 'ai-calenda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKZ4O10OJtiQ8YcB-suMthTO-BoLQa7_k',
    appId: '1:597928996925:ios:3db26f557779bb251afa54',
    messagingSenderId: '597928996925',
    projectId: 'ai-calenda',
    storageBucket: 'ai-calenda.appspot.com',
    iosBundleId: 'com.calendar.cally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKZ4O10OJtiQ8YcB-suMthTO-BoLQa7_k',
    appId: '1:597928996925:ios:47903ecc509321971afa54',
    messagingSenderId: '597928996925',
    projectId: 'ai-calenda',
    storageBucket: 'ai-calenda.appspot.com',
    iosBundleId: 'com.example.aiCalendarApp.RunnerTests',
  );
}
